name: ci_testing

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Test Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install '.[test]'

      - name: Run tests
        run: pytest -v