name: ci_testing

on:
  push:
  pull_request:

jobs:
  uv-run-tests:
    name: python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the uv project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest -v tests